version: '3.6'

networks:
  ocean-dev-network:
    name: ocean_dev_network
    driver: bridge

volumes:
  postgres-volume:

services:
  openldap:
    image: bitnami/openldap:2
    container_name: ocean_dev_container_openldap
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_PORT_NUMBER=1389
      - LDAP_ROOT="dc=example,dc=org"
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ENABLE_TLS=no
    networks:
      - ocean-dev-network
  postgres-internal:
    image: postgres:14
    container_name: ocean_dev_container_postgres_internal
    command: postgres -c config_file=/etc/postgresql.conf
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - ocean-dev-network
    volumes:
      - ./config/postgres.conf:/etc/postgresql.conf
      - postgres-volume:/var/liba/postgresql/data
      - ./config/schema.sql:/docker-entrypoint-initdb.d/schema.sql
