version: '3.6'

networks:
  ocean-dev-network:
    name: ocean_dev_network
    driver: bridge

services:
  openldap:
    image: bitnami/openldap:2
    container_name: ocean_dev_container_openldap
    ports:
      - "1389:1389"
      - "1636:1636"
    environment:
      - LDAP_PORT_NUMBER=1389
      - LDAP_ROOT="dc=example,dc=org"
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_USERS=user01,user02
      - LDAP_PASSWORDS=password1,password2
      - LDAP_ENABLE_TLS=no
    networks:
      - ocean-dev-network
