name: Frontend Code Quality

on:
  push:
    branches:
      - main
    paths:
      - ocean-frontend/**
  pull_request:
    paths:
      - ocean-frontend/**

defaults:
  run:
    working-directory: ./ocean-frontend

jobs:
  build-frontend-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3

      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install npm dependencies
        run: npm install

      - name: ESLint validation
        run: npm run lint

      - name: Run tests and collect coverage
        run: npm run test -- --coverage .

      - name: Upload coverage data to Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: ocean-frontend/coverage

      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: frontend
          verbose: true
